name: my_plugin_platform_interface
description: A common platform interface for the my_plugin plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
