// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** An enum representing test values. */
enum class TestEnum(val raw: Int) {
  /** The first value. */
  VALUE1(0),
  /** The second value. */
  VALUE2(1),
  /** The third value. */
  VALUE3(2);

  companion object {
    fun ofRaw(raw: Int): TestEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** An enum representing test values. */
enum class TestEnum1(val raw: Int) {
  /** The first value. */
  VALUE1(0),
  /** The second value. */
  VALUE2(1),
  /** The third value. */
  VALUE3(2);

  companion object {
    fun ofRaw(raw: Int): TestEnum1? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Response class
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Response (
  val model: TestModel2
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Response {
      val model = pigeonVar_list[0] as TestModel2
      return Response(model)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      model,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Response) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A model representing test data and its associated [TestModel3] model.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TestModel2 (
  /** The data string for this model. */
  val data: String,
  /** The model associated with this model. */
  val model: TestModel3
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TestModel2 {
      val data = pigeonVar_list[0] as String
      val model = pigeonVar_list[1] as TestModel3
      return TestModel2(data, model)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      model,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TestModel2) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A model representing test data and its associated [TestModel3] model.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TestModel (
  /** The data string for this model. */
  val data: String,
  /** The model associated with this model. */
  val model: TestModel3,
  /** The enum value associated with this model. */
  val enumValue: TestEnum1
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TestModel {
      val data = pigeonVar_list[0] as String
      val model = pigeonVar_list[1] as TestModel3
      val enumValue = pigeonVar_list[2] as TestEnum1
      return TestModel(data, model, enumValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      model,
      enumValue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TestModel) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A model representing test data and its associated [TestEnum] value.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TestModel3 (
  /** The data string for this model. */
  val data: String,
  /** The enum value associated with this model. */
  val enumValue: TestEnum
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TestModel3 {
      val data = pigeonVar_list[0] as String
      val enumValue = pigeonVar_list[1] as TestEnum
      return TestModel3(data, enumValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      enumValue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TestModel3) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TestEnum.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TestEnum1.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Response.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TestModel2.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TestModel.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TestModel3.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TestEnum -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is TestEnum1 -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is Response -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is TestModel2 -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TestModel -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is TestModel3 -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface Messages {
  fun getTestModel(model: TestModel2): TestModel
  fun testVoid()
  fun getResponse(): Response

  companion object {
    /** The codec used by Messages. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `Messages` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: Messages?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_plugin_android.Messages.getTestModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelArg = args[0] as TestModel2
            val wrapped: List<Any?> = try {
              listOf(api.getTestModel(modelArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_plugin_android.Messages.testVoid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.testVoid()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_plugin_android.Messages.getResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getResponse())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
