name: my_plugin_android
description: Android implementation of the my_plugin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

flutter:
  plugin:
    implements: my_plugin
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: MyPluginPlugin
        dartPluginClass: MyPluginAndroid

dependencies:
  flutter:
    sdk: flutter
  my_plugin_platform_interface:
    path: ../my_plugin_platform_interface
  pigeon_gen_cli:
    path: ../../../pigeon_gen_cli

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^26.0.1
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
