name: pigeon_gen_cli
description: A CLI to generate a flattened pigeon file by importing classes from
  multiple files into a single file.
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^7.4.0
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  path: ^1.9.0
  pub_updater: ^0.5.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.9.0
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

executables:
  pigeon_gen_cli:
