// Auto-generated by pigeon_gen_cli
// DO NOT EDIT
// Generated on 2025-10-09T16:09:29.335554

import 'package:pigeon/pigeon.dart';

@ConfigurePigeon(
  PigeonOptions(
    dartOut: 'lib/src/messages.g.dart',
    javaOptions: JavaOptions(package: 'io.flutter.plugins.urllauncher'),
    javaOut:
        'android/src/main/java/io/flutter/plugins/urllauncher/Messages.java',
    copyrightHeader: 'pigeons/copyright.txt',
  ),
)
@HostApi()
abstract class Messages {
  TestModel getTestModel(TestModel2 model);

  void testVoid();

  Response getResponse();
}

/// Response class
class Response {
  Response({required this.model});

  final TestModel2 model;
}

/// An enum representing test values.
enum TestEnum {
  /// The first value.
  value1,

  /// The second value.
  value2,

  /// The third value.
  value3,
}

/// An enum representing test values.
enum TestEnum1 {
  /// The first value.
  value1,

  /// The second value.
  value2,

  /// The third value.
  value3,
}

/// A model representing test data and its associated [TestEnum] value.
class TestModel3 {
  /// Creates a [TestModel3] with the given [data] and [enumValue].
  const TestModel3({required this.data, required this.enumValue});

  /// The data string for this model.
  final String data;

  /// The enum value associated with this model.
  final TestEnum enumValue;
}

/// A model representing test data and its associated [TestModel3] model.
class TestModel {
  /// Creates a [TestModel] with the given [data], [model], and [enumValue].
  const TestModel({
    required this.data,
    required this.model,
    required this.enumValue,
  });

  /// The data string for this model.
  final String data;

  /// The model associated with this model.
  final TestModel3 model;

  /// The enum value associated with this model.
  final TestEnum1 enumValue;
}

/// A model representing test data and its associated [TestModel3] model.
class TestModel2 {
  /// Creates a [TestModel2] with the given [data] and [model].
  const TestModel2({required this.data, required this.model});

  /// The data string for this model.
  final String data;

  /// The model associated with this model.
  final TestModel3 model;
}
